[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "open_robotics"
authors = [{name = "Du Yong Quan", email = "quandy2020@126.com"}]
dynamic = ["version", "description"]
